"use server";

import { dropCreateSchema } from "@/lib/admin/schemas";
import { toIso } from "@/app/admin/drops/form-utils";
import { resolveIntakeCredential, type IntakeLinkFailure } from "./session";
import { countSubmission } from "./links";
import { verifyUploadReceipt } from "./token";
import { extractDropFields, todayCentral } from "./extract";
import { submitPayloadSchema, type ExtractedDraft, type RequiredDraftField } from "./schemas";
import {
  assertImageAllowed,
  getLastPublishedPhoto,
  reusedPhotoProvenance,
  type LastPhoto,
} from "./images";
import { insertSubmission } from "./db";

/**
 * Server actions reachable from the restaurant's intake page.
 *
 * Three rules hold across every action in this file:
 *   1. The restaurant id comes from `resolveIntakeCredential()` and from
 *      nowhere else. Nothing the browser sends can widen its scope.
 *   2. The LLM is only ever reached through `extractDropFields`, which
 *      returns a plain validated object. No action here lets a model
 *      decide what gets written.
 *   3. Nothing here creates, updates, or publishes a `drop_items` row.
 *      The only write is one `drop_submissions` insert.
 */

// A drop id is generated by the operator's review page at publish time,
// once collisions can actually be resolved against live data. This
// placeholder exists solely so the submission can be validated by the
// REAL `dropCreateSchema` — the same schema `createDrop()` enforces —
// rather than by a parallel copy of its rules that could drift.
const VALIDATION_PLACEHOLDER_ID = "pending-submission";

export type InterpretResult =
  | {
      ok: true;
      draft: ExtractedDraft;
      missing: RequiredDraftField[];
      anchorDate: string;
      /** True when the model could not be used and every field must be asked. */
      degraded: boolean;
    }
  | { ok: false; error: string };

/**
 * Turn the restaurant's message into candidate fields.
 *
 * A provider failure is NOT an error the restaurant has to care about:
 * we return an all-null draft with `degraded: true`, and the UI asks
 * every question instead. Failing closed means asking, never assuming.
 */
export async function interpretMessage(
  credential: string,
  message: string,
): Promise<InterpretResult> {
  const link = await resolveIntakeCredential(credential);
  if (!link.ok) return { ok: false, error: linkError(link.reason) };

  const trimmed = (message ?? "").trim();
  if (!trimmed) return { ok: false, error: "Tell us about your drop first." };
  if (trimmed.length > 4000) {
    return { ok: false, error: "That message is too long — please shorten it." };
  }

  const anchorDate = todayCentral();
  const result = await extractDropFields(trimmed);

  if (!result.ok) {
    return {
      ok: true,
      draft: {
        title: null,
        price: null,
        original_price: null,
        total_spots: null,
        pickup_date: null,
        pickup_start_time: null,
        pickup_end_time: null,
      },
      missing: result.missing,
      anchorDate,
      degraded: true,
    };
  }

  return {
    ok: true,
    draft: result.draft,
    missing: result.missing,
    anchorDate,
    degraded: false,
  };
}

export type LastPhotoResult = { ok: true; photo: LastPhoto | null } | { ok: false; error: string };

/**
 * The restaurant's own most recent published photo, if any.
 * Scoped by the token's restaurant id — this is the only way the reuse
 * option can ever be populated.
 */
export async function getReusablePhoto(credential: string): Promise<LastPhotoResult> {
  const link = await resolveIntakeCredential(credential);
  if (!link.ok) return { ok: false, error: linkError(link.reason) };
  const photo = await getLastPublishedPhoto(link.restaurant.id);
  return { ok: true, photo };
}

export type SubmitResult =
  | { ok: true; submissionId: string; duplicate: boolean }
  | { ok: false; error: string; fieldErrors?: Record<string, string[]> };

/**
 * Create exactly one submission for operator review.
 *
 * This is the end of the restaurant's journey. It does not publish, does
 * not touch `drop_items`, and does not make the drop visible anywhere.
 */
export async function submitDropForReview(
  credential: string,
  payload: unknown,
): Promise<SubmitResult> {
  const link = await resolveIntakeCredential(credential);
  if (!link.ok) return { ok: false, error: linkError(link.reason) };

  const parsed = submitPayloadSchema.safeParse(payload);
  if (!parsed.success) {
    const flat = parsed.error.flatten();
    return {
      ok: false,
      error: "Please check the highlighted fields",
      fieldErrors: flat.fieldErrors as Record<string, string[]>,
    };
  }
  const input = parsed.data;

  // ── Deterministic validation stays authoritative ──────────────────
  // Convert the America/Chicago wall clock to UTC instants with the SAME
  // converter the Studio form uses, then run the SAME zod schema
  // `createDrop()` runs. Pickup-window bounds, price/original_price
  // ordering, positive spots and "end_time must be in the future" are all
  // enforced here by the real rule, not a copy of it.
  const startIso = toIso(`${input.draft.pickup_date}T${input.draft.pickup_start_time}`);
  const endIso = toIso(`${input.draft.pickup_date}T${input.draft.pickup_end_time}`);

  const validation = dropCreateSchema.safeParse({
    id: VALIDATION_PLACEHOLDER_ID,
    title: input.draft.title,
    restaurant_id: link.restaurant.id,
    image_url: input.image_url,
    price: input.draft.price,
    original_price: input.draft.original_price,
    total_spots: input.draft.total_spots,
    start_time: startIso,
    end_time: endIso,
    // Explicitly inert: this payload is validated, never inserted.
    is_active: false,
    is_hero: false,
    priority: 0,
  });

  if (!validation.success) {
    const flat = validation.error.flatten();
    const fieldErrors = flat.fieldErrors as Record<string, string[]>;
    const first =
      Object.values(fieldErrors).flat()[0] ?? "Those details don't look right yet";
    return { ok: false, error: first, fieldErrors };
  }

  // ── Image authorization (cross-tenant boundary) ───────────────────
  const imageCheck = await assertImageAllowed(
    link.restaurant.id,
    input.image_url,
    input.image_source,
  );
  if (!imageCheck.ok) {
    return { ok: false, error: imageCheck.error, fieldErrors: { image_url: [imageCheck.error] } };
  }

  // ── Provenance, from a source the restaurant cannot author ────────
  let provenance: Record<string, unknown>;
  if (input.image_source === "upload") {
    const verified = await verifyUploadReceipt(input.upload_receipt, {
      restaurantId: link.restaurant.id,
      imageUrl: input.image_url,
    });
    if (!verified) {
      const message = "We couldn't verify that photo upload. Please add the photo again.";
      return { ok: false, error: message, fieldErrors: { image_url: [message] } };
    }
    provenance = verified;
  } else {
    const last = await getLastPublishedPhoto(link.restaurant.id);
    // `assertImageAllowed` already proved this exists and matches.
    provenance = last
      ? (reusedPhotoProvenance(last) as unknown as Record<string, unknown>)
      : {};
  }

  // ── One idempotent row ────────────────────────────────────────────
  const inserted = await insertSubmission({
    restaurant_id: link.restaurant.id,
    raw_message: input.raw_message,
    draft: input.draft,
    image_url: input.image_url,
    image_source: input.image_source,
    image_provenance: provenance,
    idempotency_key: input.idempotency_key,
    // "which link produced this". For a short code that is the
    // intake_links row id; for a legacy JWT it is the token's jti.
    intake_token_jti: link.linkId,
    intake_token_issued_at: link.issuedAt?.toISOString() ?? null,
    intake_token_expires_at: link.expiresAt?.toISOString() ?? null,
    intake_session_id: input.intake_session_id,
  });

  if (!inserted.ok) return { ok: false, error: inserted.error };

  // Count a real submission against the short link that produced it, so
  // an operator can see a link is being used. Only on a genuinely new
  // row — a duplicate is the same submission arriving twice, not a
  // second use. Bookkeeping: never allowed to fail the submission.
  if (link.kind === "short_code" && link.link && !inserted.duplicate) {
    void countSubmission(link.link.id, link.link.use_count);
  }

  return {
    ok: true,
    submissionId: inserted.submission.id,
    duplicate: inserted.duplicate,
  };
}

// Not exported: a "use server" module may only export async functions.
function linkError(reason: IntakeLinkFailure): string {
  if (reason === "inactive") {
    return "This restaurant is not currently active on DealsPro. Please contact us.";
  }
  if (reason === "unconfigured") {
    return "Restaurant intake is not configured yet. Please contact DealsPro.";
  }
  // "invalid", "expired", "revoked" and "legacy_disabled" all collapse to
  // one message on purpose: telling a visitor which of those applies
  // would confirm to someone probing codes that they had found a real
  // link. Studio shows operators the real state.
  return "This link is no longer valid. Please ask DealsPro for a new one.";
}
